---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    chef_license: accept
    local_mode: true

verifier:
  name: inspec

platforms:
  - name: debian-9
  - name: tas50/windows_10
    os_type: windows
    transport:
      name: winrm
    driver:
      customize:
        memory: 2048

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
